(defun tdk_start()
  (load "C:\\_PROJECTS\\TDK\\tdk_all2sof.lsp")
  (load "C:\\_PROJECTS\\TDK\\tdk_dlugosc_preta.lsp")
  (load "C:\\_PROJECTS\\TDK\\tdk_izoluj_warstwy_dk.lsp")
  (load "C:\\_PROJECTS\\TDK\\tdk_liczba_pretow.lsp")
  (load "C:\\_PROJECTS\\TDK\\tdk_polacz_polilinie.lsp")
  (load "C:\\_PROJECTS\\TDK\\tdk_przetnij_w_punkcie.lsp")
  (princ)
)
(tdk_start)